# Generated by Django 4.1.2 on 2023-01-29 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_newuser_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
