# Generated by Django 3.2.3 on 2022-10-24 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('deivceid', models.IntegerField(db_column='DeivceId', primary_key=True, serialize=False)),
                ('devicename', models.CharField(blank=True, db_column='DeviceName', max_length=10, null=True)),
                ('ownerid', models.ForeignKey(blank=True, db_column='OwnerId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
