# Generated by Django 3.2.3 on 2022-10-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20221024_1828'),
        ('packets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packets',
            name='deviceid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.devices'),
        ),
        migrations.AlterField(
            model_name='packets',
            name='packetinfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
